general_cfg:
  algo_name: SAC_D
  device: cuda
  env_name: CartPole-v1
  new_step_api: True
  wrapper: null
  mode: train
  load_checkpoint: false
  load_path: Train_CartPole-v1_DQN_20221026-054757
  max_steps: 200
  save_fig: true
  seed: 0
  show_fig: false
  test_eps: 10
  train_eps: 200
algo_cfg:
  alpha: 0.2
  epsilon_decay: 500
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.95
  lr: 0.0001  
  target_update: 1