general_cfg:
  algo_name: DQN
  device: cpu
  env_name: gym
  mode: train
  n_workers: 1 # number of workers for parallel training
  load_checkpoint: false
  load_path: Train_CartPole-v1_DQN_20221026-054757
  max_steps: 200
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  train_eps: 100
algo_cfg:
  value_layers:
    - layer_type: linear
      layer_dim: [256]
      activation: relu
    - layer_type: linear
      layer_dim: [256]
      activation: relu
  buffer_type: REPLAY_QUE
  buffer_size: 100000
  batch_size: 128
  epsilon_decay: 200
  epsilon_end: 0.005
  epsilon_start: 0.95
  gamma: 0.95
  lr: 0.0001
  target_update: 4
env_cfg:
  id: CartPole-v1
  new_step_api: true
  render_mode: null