general_cfg:
  algo_name: DQN_new # algo name
  device: cpu # device, cpu or cuda
  env_name: gym # env name, differ from env_id in env_cfgs
  mode: test # run mode: train, test
  collect_traj: true
  mp_backend: single # multi-processing mode: null(default), ray
  n_workers: 1 # number of workers if using multi-processing, default 1
  load_checkpoint: true # if load checkpoint or not
  load_path: Train_single_CartPole-v1_DQN_new_20230515-130936 # if load checkpoint, then config path in 'tasks' dir
  load_model_step: best
  max_episode: 10 # max episodes, set -1 to keep running
  max_step: 200 # max steps per episode
  seed: 1 # random seed, set 0 not to use seed
  online_eval: true # if online eval or not
  online_eval_episode: 10 # online eval episodes
  model_save_fre: 500 # update step frequency of saving model
  save_best_model: # if save the best model or not, online_eval must be true)
  save_fig: true # if save fig or not
  show_fig: false # if show fig or not

algo_cfg:
  value_layers:
    - layer_type: linear
      layer_dim: [256]
      activation: relu
    - layer_type: linear
      layer_dim: [256]
      activation: relu
  batch_size: 64
  buffer_type: REPLAY_QUE
  buffer_size: 100000
  epsilon_decay: 500
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.95
  lr: 0.0001
  target_update: 4
env_cfg:
  id: CartPole-v1
  render_mode: human