general_cfg:
  algo_name: MO-QLearning
  device: cpu
  env_name: deep-sea-treasure-v0
  wrapper: envs.wrappers.DeepSeaTreasure
  render: True
  mode: test
  load_checkpoint: true
  load_path: Test_deep-sea-treasure-v0_MO-QLearning_20230329-234802
  max_steps: 100
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  train_eps: 300
algo_cfg:
  epsilon_decay: 300
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.99
  lr: 0.1
