general_cfg:
  algo_name: DDPG
  device: cuda
  env_name: gym
  eval_eps: 10
  eval_per_episode: 5
  load_checkpoint: false
  load_path: Train_CartPole-v1_DQN_20221026-054757
  max_steps: 200
  mode: train
  new_step_api: true
  render: false
  save_fig: true
  seed: 10
  show_fig: false
  test_eps: 10
  train_eps: 400
  wrapper: null
algo_cfg:
  actor_hidden_dim: 256
  actor_lr: 0.0001
  batch_size: 128
  buffer_size: 8000
  critic_hidden_dim: 256
  critic_lr: 0.001
  gamma: 0.99
  tau: 0.001
env_cfg:
  id: Pendulum-v1
  new_step_api: true